### ISSUE TITLE
Importing etw causes log level to be set

### ISSUE THREAD

**Issue by ptc-aeveritt** [fireeye/pywintrace#23] opened 2019-04-24 11:47 UTC
I am using the 0.2.0 package from PyPi.

When I 'import etw' logging is configured (in common.py), this caused a problem because my own call to logging.basicConfig happened later and most of my logging disappears.

I have modified this issue based on my later findings, as basicConfig is called when the first log call is made I suggest removing the call to logging.basicConfig in etw/common.py but am happy to hear alternative suggestions.

**Comment by abergl** [comment] 2019-04-30 17:56
Branched for fix and PR submitted.

**Comment by abergl** [comment] 2019-04-30 18:09
Fix is in master. If you would please confirm the issue is resolved with the version in master I can close this.

**Comment by ptc-aeveritt** [comment] 2019-05-01 08:45
Thank you for the fast turnaround - your fix solves the issue I was seeing :)

**Comment by abergl** [comment] 2019-05-01 13:01
No problem. Closing issue.

**Closed by abergl** 2019-05-01 13:01 UTC
Labels: bug
