### ISSUE TITLE
No events captured

### ISSUE THREAD

**Issue by airhack87** [fireeye/pywintrace#2] opened 2017-09-29 18:31 UTC
I am testing the module and when I fire  up the browser and connect to some website, nothing seems to be logged. When I enable the EWT from the event log, event are logged in the event log.
![nothing-logged](https://user-images.githubusercontent.com/10479886/31030303-8840f03c-a55d-11e7-9445-50cb5a3a041e.png)

**Comment by abergl** [comment] 2017-09-29 20:27
Without knowing any other details I would suggest that you try a capture without using default filters.

**Comment by airhack87** [comment] 2017-09-30 07:52
Done that too!
Its a windows 10 box.
Also re-verified the GUID for the Microsoft-Windows-WinINet and Microsoft-Windows-WinINet-Capture which are correct mapped to ones in the script.
Any pointers pls.

**Comment by abergl** [comment] 2017-10-01 15:47
Perhaps a previous capture session was not shut down properly. You can check this by typing "logman -ets" to see currently running sessions.

**Comment by piggum** [comment] 2017-10-16 01:11
@airhack87 we are unable to reproduce this issue. Were you able to resolve this on your own?

**Comment by airhack87** [comment] 2017-10-16 16:52
Yea.. Needed elevated privileges in cmd to run it. Caught it just in time.
Also tested it with the Microsoft-Windows-DNS-Client to catch DNS queries.. works like a charm!!

**Comment by abergl** [comment] 2017-10-16 16:54
Good to hear. Let us know if you have any more questions/issues. Closing issue.

**Closed** 2017-10-16 16:55 UTC
